[workspace]
members = [
    "tcc-sys"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
eyre = "0.6.8"

[package]
name = "tcc-rs"
version.workspace = true
edition.workspace = true

[dependencies]
